### ISSUE TITLE
undefined method `hx' for #<ActionView::Base:0x00000000007620>

### ISSUE THREAD

**Issue by wilsonsilva** [guilleiguaran/rails-htmx#1]
It took me a while to realise that the README.md was talking about a helper method (`hx`) that does not exist in the latest published version of the gem (`0.1.2`).

**Comment by guilleiguaran** [comment]
Sorry, I'll publish a new version now

**Comment by guilleiguaran** [comment]
Published: https://rubygems.org/gems/rails-htmx/versions/0.1.3
